// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntContainerOuterClass.proto

package org.hyperledger.fabric.example;

public final class IntContainerOuterClass {
  private IntContainerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IntContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IntContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string __guid = 1;</code>
     */
    java.lang.String getGuid();
    /**
     * <code>string __guid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGuidBytes();

    /**
     * <code>bytes x = 2;</code>
     */
    com.google.protobuf.ByteString getX();

    /**
     * <code>string s = 3;</code>
     */
    java.lang.String getS();
    /**
     * <code>string s = 3;</code>
     */
    com.google.protobuf.ByteString
        getSBytes();

    /**
     * <code>bool b = 4;</code>
     */
    boolean getB();
  }
  /**
   * Protobuf type {@code IntContainer}
   */
  public  static final class IntContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IntContainer)
      IntContainerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IntContainer.newBuilder() to construct.
    private IntContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IntContainer() {
      Guid_ = "";
      x_ = com.google.protobuf.ByteString.EMPTY;
      s_ = "";
      b_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IntContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              Guid_ = s;
              break;
            }
            case 18: {

              x_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              s_ = s;
              break;
            }
            case 32: {

              b_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.class, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder.class);
    }

    public static final int __GUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object Guid_;
    /**
     * <code>string __guid = 1;</code>
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = Guid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Guid_ = s;
        return s;
      }
    }
    /**
     * <code>string __guid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      java.lang.Object ref = Guid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString x_;
    /**
     * <code>bytes x = 2;</code>
     */
    public com.google.protobuf.ByteString getX() {
      return x_;
    }

    public static final int S_FIELD_NUMBER = 3;
    private volatile java.lang.Object s_;
    /**
     * <code>string s = 3;</code>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s_ = s;
        return s;
      }
    }
    /**
     * <code>string s = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B_FIELD_NUMBER = 4;
    private boolean b_;
    /**
     * <code>bool b = 4;</code>
     */
    public boolean getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, Guid_);
      }
      if (!x_.isEmpty()) {
        output.writeBytes(2, x_);
      }
      if (!getSBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, s_);
      }
      if (b_ != false) {
        output.writeBool(4, b_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, Guid_);
      }
      if (!x_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, x_);
      }
      if (!getSBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, s_);
      }
      if (b_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer other = (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) obj;

      boolean result = true;
      result = result && getGuid()
          .equals(other.getGuid());
      result = result && getX()
          .equals(other.getX());
      result = result && getS()
          .equals(other.getS());
      result = result && (getB()
          == other.getB());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + __GUID_FIELD_NUMBER;
      hash = (53 * hash) + getGuid().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + S_FIELD_NUMBER;
      hash = (53 * hash) + getS().hashCode();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getB());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IntContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IntContainer)
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.class, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder.class);
      }

      // Construct using org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        Guid_ = "";

        x_ = com.google.protobuf.ByteString.EMPTY;

        s_ = "";

        b_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainer_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getDefaultInstanceForType() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer build() {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer buildPartial() {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer result = new org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer(this);
        result.Guid_ = Guid_;
        result.x_ = x_;
        result.s_ = s_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) {
          return mergeFrom((org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer other) {
        if (other == org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance()) return this;
        if (!other.getGuid().isEmpty()) {
          Guid_ = other.Guid_;
          onChanged();
        }
        if (other.getX() != com.google.protobuf.ByteString.EMPTY) {
          setX(other.getX());
        }
        if (!other.getS().isEmpty()) {
          s_ = other.s_;
          onChanged();
        }
        if (other.getB() != false) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object Guid_ = "";
      /**
       * <code>string __guid = 1;</code>
       */
      public java.lang.String getGuid() {
        java.lang.Object ref = Guid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          Guid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string __guid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGuidBytes() {
        java.lang.Object ref = Guid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Guid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string __guid = 1;</code>
       */
      public Builder setGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        Guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string __guid = 1;</code>
       */
      public Builder clearGuid() {
        
        Guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      /**
       * <code>string __guid = 1;</code>
       */
      public Builder setGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        Guid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString x_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes x = 2;</code>
       */
      public com.google.protobuf.ByteString getX() {
        return x_;
      }
      /**
       * <code>bytes x = 2;</code>
       */
      public Builder setX(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes x = 2;</code>
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }

      private java.lang.Object s_ = "";
      /**
       * <code>string s = 3;</code>
       */
      public java.lang.String getS() {
        java.lang.Object ref = s_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          s_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string s = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        java.lang.Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string s = 3;</code>
       */
      public Builder setS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string s = 3;</code>
       */
      public Builder clearS() {
        
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>string s = 3;</code>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        s_ = value;
        onChanged();
        return this;
      }

      private boolean b_ ;
      /**
       * <code>bool b = 4;</code>
       */
      public boolean getB() {
        return b_;
      }
      /**
       * <code>bool b = 4;</code>
       */
      public Builder setB(boolean value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool b = 4;</code>
       */
      public Builder clearB() {
        
        b_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IntContainer)
    }

    // @@protoc_insertion_point(class_scope:IntContainer)
    private static final org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer();
    }

    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IntContainer>
        PARSER = new com.google.protobuf.AbstractParser<IntContainer>() {
      @java.lang.Override
      public IntContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IntContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IntContainer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IntContainerOrGUIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IntContainerOrGUID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.IntContainer obj = 1;</code>
     */
    boolean hasObj();
    /**
     * <code>.IntContainer obj = 1;</code>
     */
    org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getObj();
    /**
     * <code>.IntContainer obj = 1;</code>
     */
    org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder getObjOrBuilder();

    /**
     * <code>string guid = 2;</code>
     */
    java.lang.String getGuid();
    /**
     * <code>string guid = 2;</code>
     */
    com.google.protobuf.ByteString
        getGuidBytes();

    public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.EitherCase getEitherCase();
  }
  /**
   * Protobuf type {@code IntContainerOrGUID}
   */
  public  static final class IntContainerOrGUID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IntContainerOrGUID)
      IntContainerOrGUIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IntContainerOrGUID.newBuilder() to construct.
    private IntContainerOrGUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IntContainerOrGUID() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IntContainerOrGUID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder subBuilder = null;
              if (eitherCase_ == 1) {
                subBuilder = ((org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_).toBuilder();
              }
              either_ =
                  input.readMessage(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_);
                either_ = subBuilder.buildPartial();
              }
              eitherCase_ = 1;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              eitherCase_ = 2;
              either_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainerOrGUID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainerOrGUID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.class, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.Builder.class);
    }

    private int eitherCase_ = 0;
    private java.lang.Object either_;
    public enum EitherCase
        implements com.google.protobuf.Internal.EnumLite {
      OBJ(1),
      GUID(2),
      EITHER_NOT_SET(0);
      private final int value;
      private EitherCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EitherCase valueOf(int value) {
        return forNumber(value);
      }

      public static EitherCase forNumber(int value) {
        switch (value) {
          case 1: return OBJ;
          case 2: return GUID;
          case 0: return EITHER_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EitherCase
    getEitherCase() {
      return EitherCase.forNumber(
          eitherCase_);
    }

    public static final int OBJ_FIELD_NUMBER = 1;
    /**
     * <code>.IntContainer obj = 1;</code>
     */
    public boolean hasObj() {
      return eitherCase_ == 1;
    }
    /**
     * <code>.IntContainer obj = 1;</code>
     */
    public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getObj() {
      if (eitherCase_ == 1) {
         return (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_;
      }
      return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
    }
    /**
     * <code>.IntContainer obj = 1;</code>
     */
    public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder getObjOrBuilder() {
      if (eitherCase_ == 1) {
         return (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_;
      }
      return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
    }

    public static final int GUID_FIELD_NUMBER = 2;
    /**
     * <code>string guid = 2;</code>
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = "";
      if (eitherCase_ == 2) {
        ref = either_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (eitherCase_ == 2) {
          either_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string guid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      java.lang.Object ref = "";
      if (eitherCase_ == 2) {
        ref = either_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (eitherCase_ == 2) {
          either_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eitherCase_ == 1) {
        output.writeMessage(1, (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_);
      }
      if (eitherCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, either_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eitherCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_);
      }
      if (eitherCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, either_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID other = (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID) obj;

      boolean result = true;
      result = result && getEitherCase().equals(
          other.getEitherCase());
      if (!result) return false;
      switch (eitherCase_) {
        case 1:
          result = result && getObj()
              .equals(other.getObj());
          break;
        case 2:
          result = result && getGuid()
              .equals(other.getGuid());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (eitherCase_) {
        case 1:
          hash = (37 * hash) + OBJ_FIELD_NUMBER;
          hash = (53 * hash) + getObj().hashCode();
          break;
        case 2:
          hash = (37 * hash) + GUID_FIELD_NUMBER;
          hash = (53 * hash) + getGuid().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IntContainerOrGUID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IntContainerOrGUID)
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainerOrGUID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainerOrGUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.class, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.Builder.class);
      }

      // Construct using org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eitherCase_ = 0;
        either_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.internal_static_IntContainerOrGUID_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID getDefaultInstanceForType() {
        return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID build() {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID buildPartial() {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID result = new org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID(this);
        if (eitherCase_ == 1) {
          if (objBuilder_ == null) {
            result.either_ = either_;
          } else {
            result.either_ = objBuilder_.build();
          }
        }
        if (eitherCase_ == 2) {
          result.either_ = either_;
        }
        result.eitherCase_ = eitherCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID) {
          return mergeFrom((org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID other) {
        if (other == org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID.getDefaultInstance()) return this;
        switch (other.getEitherCase()) {
          case OBJ: {
            mergeObj(other.getObj());
            break;
          }
          case GUID: {
            eitherCase_ = 2;
            either_ = other.either_;
            onChanged();
            break;
          }
          case EITHER_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eitherCase_ = 0;
      private java.lang.Object either_;
      public EitherCase
          getEitherCase() {
        return EitherCase.forNumber(
            eitherCase_);
      }

      public Builder clearEither() {
        eitherCase_ = 0;
        either_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder> objBuilder_;
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public boolean hasObj() {
        return eitherCase_ == 1;
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer getObj() {
        if (objBuilder_ == null) {
          if (eitherCase_ == 1) {
            return (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_;
          }
          return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
        } else {
          if (eitherCase_ == 1) {
            return objBuilder_.getMessage();
          }
          return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public Builder setObj(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer value) {
        if (objBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          either_ = value;
          onChanged();
        } else {
          objBuilder_.setMessage(value);
        }
        eitherCase_ = 1;
        return this;
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public Builder setObj(
          org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder builderForValue) {
        if (objBuilder_ == null) {
          either_ = builderForValue.build();
          onChanged();
        } else {
          objBuilder_.setMessage(builderForValue.build());
        }
        eitherCase_ = 1;
        return this;
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public Builder mergeObj(org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer value) {
        if (objBuilder_ == null) {
          if (eitherCase_ == 1 &&
              either_ != org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance()) {
            either_ = org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.newBuilder((org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_)
                .mergeFrom(value).buildPartial();
          } else {
            either_ = value;
          }
          onChanged();
        } else {
          if (eitherCase_ == 1) {
            objBuilder_.mergeFrom(value);
          }
          objBuilder_.setMessage(value);
        }
        eitherCase_ = 1;
        return this;
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public Builder clearObj() {
        if (objBuilder_ == null) {
          if (eitherCase_ == 1) {
            eitherCase_ = 0;
            either_ = null;
            onChanged();
          }
        } else {
          if (eitherCase_ == 1) {
            eitherCase_ = 0;
            either_ = null;
          }
          objBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder getObjBuilder() {
        return getObjFieldBuilder().getBuilder();
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder getObjOrBuilder() {
        if ((eitherCase_ == 1) && (objBuilder_ != null)) {
          return objBuilder_.getMessageOrBuilder();
        } else {
          if (eitherCase_ == 1) {
            return (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_;
          }
          return org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.IntContainer obj = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder> 
          getObjFieldBuilder() {
        if (objBuilder_ == null) {
          if (!(eitherCase_ == 1)) {
            either_ = org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.getDefaultInstance();
          }
          objBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer.Builder, org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrBuilder>(
                  (org.hyperledger.fabric.example.IntContainerOuterClass.IntContainer) either_,
                  getParentForChildren(),
                  isClean());
          either_ = null;
        }
        eitherCase_ = 1;
        onChanged();;
        return objBuilder_;
      }

      /**
       * <code>string guid = 2;</code>
       */
      public java.lang.String getGuid() {
        java.lang.Object ref = "";
        if (eitherCase_ == 2) {
          ref = either_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (eitherCase_ == 2) {
            either_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string guid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGuidBytes() {
        java.lang.Object ref = "";
        if (eitherCase_ == 2) {
          ref = either_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (eitherCase_ == 2) {
            either_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string guid = 2;</code>
       */
      public Builder setGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  eitherCase_ = 2;
        either_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string guid = 2;</code>
       */
      public Builder clearGuid() {
        if (eitherCase_ == 2) {
          eitherCase_ = 0;
          either_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string guid = 2;</code>
       */
      public Builder setGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        eitherCase_ = 2;
        either_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IntContainerOrGUID)
    }

    // @@protoc_insertion_point(class_scope:IntContainerOrGUID)
    private static final org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID();
    }

    public static org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IntContainerOrGUID>
        PARSER = new com.google.protobuf.AbstractParser<IntContainerOrGUID>() {
      @java.lang.Override
      public IntContainerOrGUID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntContainerOrGUID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IntContainerOrGUID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IntContainerOrGUID> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.example.IntContainerOuterClass.IntContainerOrGUID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntContainer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntContainerOrGUID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntContainerOrGUID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034IntContainerOuterClass.proto\"?\n\014IntCon" +
      "tainer\022\016\n\006__guid\030\001 \001(\t\022\t\n\001x\030\002 \001(\014\022\t\n\001s\030\003" +
      " \001(\t\022\t\n\001b\030\004 \001(\010\"L\n\022IntContainerOrGUID\022\034\n" +
      "\003obj\030\001 \001(\0132\r.IntContainerH\000\022\016\n\004guid\030\002 \001(" +
      "\tH\000B\010\n\006eitherB8\n\036org.hyperledger.fabric." +
      "exampleB\026IntContainerOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IntContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IntContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntContainer_descriptor,
        new java.lang.String[] { "Guid", "X", "S", "B", });
    internal_static_IntContainerOrGUID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IntContainerOrGUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntContainerOrGUID_descriptor,
        new java.lang.String[] { "Obj", "Guid", "Either", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
