// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntContainerOuterClass.proto

package edu.cmu.cs.obsidian.generated_code;

public final class IntContainerOuterClass {
  private IntContainerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IntContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IntContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes x = 1;</code>
     */
    com.google.protobuf.ByteString getX();

    /**
     * <code>string s = 2;</code>
     */
    java.lang.String getS();
    /**
     * <code>string s = 2;</code>
     */
    com.google.protobuf.ByteString
        getSBytes();

    /**
     * <code>bool b = 3;</code>
     */
    boolean getB();
  }
  /**
   * Protobuf type {@code IntContainer}
   */
  public  static final class IntContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IntContainer)
      IntContainerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IntContainer.newBuilder() to construct.
    private IntContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IntContainer() {
      x_ = com.google.protobuf.ByteString.EMPTY;
      s_ = "";
      b_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IntContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              x_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              s_ = s;
              break;
            }
            case 24: {

              b_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.internal_static_IntContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.internal_static_IntContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.class, edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString x_;
    /**
     * <code>bytes x = 1;</code>
     */
    public com.google.protobuf.ByteString getX() {
      return x_;
    }

    public static final int S_FIELD_NUMBER = 2;
    private volatile java.lang.Object s_;
    /**
     * <code>string s = 2;</code>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s_ = s;
        return s;
      }
    }
    /**
     * <code>string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B_FIELD_NUMBER = 3;
    private boolean b_;
    /**
     * <code>bool b = 3;</code>
     */
    public boolean getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!x_.isEmpty()) {
        output.writeBytes(1, x_);
      }
      if (!getSBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, s_);
      }
      if (b_ != false) {
        output.writeBool(3, b_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!x_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, x_);
      }
      if (!getSBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, s_);
      }
      if (b_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer)) {
        return super.equals(obj);
      }
      edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer other = (edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer) obj;

      boolean result = true;
      result = result && getX()
          .equals(other.getX());
      result = result && getS()
          .equals(other.getS());
      result = result && (getB()
          == other.getB());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + S_FIELD_NUMBER;
      hash = (53 * hash) + getS().hashCode();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getB());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IntContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IntContainer)
        edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.internal_static_IntContainer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.internal_static_IntContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.class, edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.Builder.class);
      }

      // Construct using edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = com.google.protobuf.ByteString.EMPTY;

        s_ = "";

        b_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.internal_static_IntContainer_descriptor;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer getDefaultInstanceForType() {
        return edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.getDefaultInstance();
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer build() {
        edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer buildPartial() {
        edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer result = new edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer(this);
        result.x_ = x_;
        result.s_ = s_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer) {
          return mergeFrom((edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer other) {
        if (other == edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer.getDefaultInstance()) return this;
        if (other.getX() != com.google.protobuf.ByteString.EMPTY) {
          setX(other.getX());
        }
        if (!other.getS().isEmpty()) {
          s_ = other.s_;
          onChanged();
        }
        if (other.getB() != false) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString x_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes x = 1;</code>
       */
      public com.google.protobuf.ByteString getX() {
        return x_;
      }
      /**
       * <code>bytes x = 1;</code>
       */
      public Builder setX(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }

      private java.lang.Object s_ = "";
      /**
       * <code>string s = 2;</code>
       */
      public java.lang.String getS() {
        java.lang.Object ref = s_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          s_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string s = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        java.lang.Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string s = 2;</code>
       */
      public Builder setS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string s = 2;</code>
       */
      public Builder clearS() {
        
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>string s = 2;</code>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        s_ = value;
        onChanged();
        return this;
      }

      private boolean b_ ;
      /**
       * <code>bool b = 3;</code>
       */
      public boolean getB() {
        return b_;
      }
      /**
       * <code>bool b = 3;</code>
       */
      public Builder setB(boolean value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool b = 3;</code>
       */
      public Builder clearB() {
        
        b_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IntContainer)
    }

    // @@protoc_insertion_point(class_scope:IntContainer)
    private static final edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer();
    }

    public static edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IntContainer>
        PARSER = new com.google.protobuf.AbstractParser<IntContainer>() {
      @java.lang.Override
      public IntContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IntContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IntContainer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.cmu.cs.obsidian.generated_code.IntContainerOuterClass.IntContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntContainer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034IntContainerOuterClass.proto\"/\n\014IntCon" +
      "tainer\022\t\n\001x\030\001 \001(\014\022\t\n\001s\030\002 \001(\t\022\t\n\001b\030\003 \001(\010B" +
      "<\n\"edu.cmu.cs.obsidian.generated_codeB\026I" +
      "ntContainerOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IntContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IntContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntContainer_descriptor,
        new java.lang.String[] { "X", "S", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
