// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestFFIOuterClass.proto

package edu.cmu.cs.obsidian.generated_code;

public final class TestFFIOuterClass {
  private TestFFIOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IO)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code IO}
   */
  public  static final class IO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IO)
      IOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IO.newBuilder() to construct.
    private IO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IO() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO)) {
        return super.equals(obj);
      }
      edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO other = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IO)
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.Builder.class);
      }

      // Construct using edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IO_descriptor;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO getDefaultInstanceForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.getDefaultInstance();
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO build() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO buildPartial() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO result = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO) {
          return mergeFrom((edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO other) {
        if (other == edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IO)
    }

    // @@protoc_insertion_point(class_scope:IO)
    private static final edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO();
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IO>
        PARSER = new com.google.protobuf.AbstractParser<IO>() {
      @java.lang.Override
      public IO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IOImplOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IOImpl)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code IOImpl}
   */
  public  static final class IOImpl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IOImpl)
      IOImplOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IOImpl.newBuilder() to construct.
    private IOImpl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IOImpl() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IOImpl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IOImpl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IOImpl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl)) {
        return super.equals(obj);
      }
      edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl other = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IOImpl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IOImpl)
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImplOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IOImpl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IOImpl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.Builder.class);
      }

      // Construct using edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_IOImpl_descriptor;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl getDefaultInstanceForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.getDefaultInstance();
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl build() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl buildPartial() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl result = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl) {
          return mergeFrom((edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl other) {
        if (other == edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IOImpl)
    }

    // @@protoc_insertion_point(class_scope:IOImpl)
    private static final edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl();
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IOImpl>
        PARSER = new com.google.protobuf.AbstractParser<IOImpl>() {
      @java.lang.Override
      public IOImpl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IOImpl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IOImpl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IOImpl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.IOImpl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test)
      TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_Test_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test)) {
        return super.equals(obj);
      }
      edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test other = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test)
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_Test_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.class, edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.Builder.class);
      }

      // Construct using edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.internal_static_Test_descriptor;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test getDefaultInstanceForType() {
        return edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.getDefaultInstance();
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test build() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test buildPartial() {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test result = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test) {
          return mergeFrom((edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test other) {
        if (other == edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Test)
    }

    // @@protoc_insertion_point(class_scope:Test)
    private static final edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test();
    }

    public static edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      @java.lang.Override
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.cmu.cs.obsidian.generated_code.TestFFIOuterClass.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IOImpl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IOImpl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TestFFIOuterClass.proto\"\004\n\002IO\"\010\n\006IOImp" +
      "l\"\006\n\004TestB7\n\"edu.cmu.cs.obsidian.generat" +
      "ed_codeB\021TestFFIOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IO_descriptor,
        new java.lang.String[] { });
    internal_static_IOImpl_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IOImpl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IOImpl_descriptor,
        new java.lang.String[] { });
    internal_static_Test_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
