// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple3OuterClass.proto

package org.hyperledger.fabric.example;

public final class Simple3OuterClass {
  private Simple3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Simple3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Simple3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes x = 1;</code>
     */
    com.google.protobuf.ByteString getX();

    /**
     * <code>bytes y = 2;</code>
     */
    com.google.protobuf.ByteString getY();
  }
  /**
   * Protobuf type {@code Simple3}
   */
  public  static final class Simple3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Simple3)
      Simple3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Simple3.newBuilder() to construct.
    private Simple3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Simple3() {
      x_ = com.google.protobuf.ByteString.EMPTY;
      y_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Simple3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              x_ = input.readBytes();
              break;
            }
            case 18: {

              y_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.example.Simple3OuterClass.internal_static_Simple3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.example.Simple3OuterClass.internal_static_Simple3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.example.Simple3OuterClass.Simple3.class, org.hyperledger.fabric.example.Simple3OuterClass.Simple3.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString x_;
    /**
     * <code>bytes x = 1;</code>
     */
    public com.google.protobuf.ByteString getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString y_;
    /**
     * <code>bytes y = 2;</code>
     */
    public com.google.protobuf.ByteString getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!x_.isEmpty()) {
        output.writeBytes(1, x_);
      }
      if (!y_.isEmpty()) {
        output.writeBytes(2, y_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!x_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, x_);
      }
      if (!y_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.example.Simple3OuterClass.Simple3)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.example.Simple3OuterClass.Simple3 other = (org.hyperledger.fabric.example.Simple3OuterClass.Simple3) obj;

      boolean result = true;
      result = result && getX()
          .equals(other.getX());
      result = result && getY()
          .equals(other.getY());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.example.Simple3OuterClass.Simple3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Simple3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Simple3)
        org.hyperledger.fabric.example.Simple3OuterClass.Simple3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.example.Simple3OuterClass.internal_static_Simple3_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.example.Simple3OuterClass.internal_static_Simple3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.example.Simple3OuterClass.Simple3.class, org.hyperledger.fabric.example.Simple3OuterClass.Simple3.Builder.class);
      }

      // Construct using org.hyperledger.fabric.example.Simple3OuterClass.Simple3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = com.google.protobuf.ByteString.EMPTY;

        y_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.example.Simple3OuterClass.internal_static_Simple3_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.Simple3OuterClass.Simple3 getDefaultInstanceForType() {
        return org.hyperledger.fabric.example.Simple3OuterClass.Simple3.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.Simple3OuterClass.Simple3 build() {
        org.hyperledger.fabric.example.Simple3OuterClass.Simple3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.example.Simple3OuterClass.Simple3 buildPartial() {
        org.hyperledger.fabric.example.Simple3OuterClass.Simple3 result = new org.hyperledger.fabric.example.Simple3OuterClass.Simple3(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.example.Simple3OuterClass.Simple3) {
          return mergeFrom((org.hyperledger.fabric.example.Simple3OuterClass.Simple3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.example.Simple3OuterClass.Simple3 other) {
        if (other == org.hyperledger.fabric.example.Simple3OuterClass.Simple3.getDefaultInstance()) return this;
        if (other.getX() != com.google.protobuf.ByteString.EMPTY) {
          setX(other.getX());
        }
        if (other.getY() != com.google.protobuf.ByteString.EMPTY) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.example.Simple3OuterClass.Simple3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.example.Simple3OuterClass.Simple3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString x_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes x = 1;</code>
       */
      public com.google.protobuf.ByteString getX() {
        return x_;
      }
      /**
       * <code>bytes x = 1;</code>
       */
      public Builder setX(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString y_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes y = 2;</code>
       */
      public com.google.protobuf.ByteString getY() {
        return y_;
      }
      /**
       * <code>bytes y = 2;</code>
       */
      public Builder setY(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = getDefaultInstance().getY();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Simple3)
    }

    // @@protoc_insertion_point(class_scope:Simple3)
    private static final org.hyperledger.fabric.example.Simple3OuterClass.Simple3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.example.Simple3OuterClass.Simple3();
    }

    public static org.hyperledger.fabric.example.Simple3OuterClass.Simple3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Simple3>
        PARSER = new com.google.protobuf.AbstractParser<Simple3>() {
      @java.lang.Override
      public Simple3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Simple3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Simple3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Simple3> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.example.Simple3OuterClass.Simple3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Simple3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Simple3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027Simple3OuterClass.proto\"\037\n\007Simple3\022\t\n\001" +
      "x\030\001 \001(\014\022\t\n\001y\030\002 \001(\014B7\n\"edu.cmu.cs.obsidia" +
      "n.generated_codeB\021Simple3OuterClassb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Simple3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Simple3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Simple3_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
